/**
 * Generates the prebuilt theme CSS files shipped on the `@dmaster/ui/themes/*`
 * subpath, from `scripts/themes.manifest.mjs` (the single source of truth).
 *
 * Each theme is a tiny override layer — it only recolors `--dm-primary` (+ its
 * foreground and the focus ring); the library's OKLCH cascade re-derives the
 * rest (`-hover`, `-text`, `-subtle`, the brand gradient) in both light and
 * dark, so the light/dark toggle keeps working. Loaded AFTER the base styles.
 *
 * A11y gate: the label colour (`fg`) MUST clear WCAG AA (>= 4.5:1) against both
 * the light and the dark fill, or the build fails — same rigor as the axe gate.
 *
 * Run from the workspace root (any cwd works — paths resolve from this file):
 *   node scripts/build-themes.mjs
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { THEMES } from './themes.manifest.mjs';

const workspaceRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(workspaceRoot, 'dist', 'dmaster-ui', 'themes');

const AA = 4.5;

/** sRGB channel (0-255) → linear light value. */
function toLinear(channel) {
  const c = channel / 255;
  return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
}

/** Relative luminance of a `#rrggbb` colour (WCAG 2.1). */
function luminance(hex) {
  const int = Number.parseInt(hex.slice(1), 16);
  const r = toLinear((int >> 16) & 0xff);
  const g = toLinear((int >> 8) & 0xff);
  const b = toLinear(int & 0xff);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/** WCAG contrast ratio between two `#rrggbb` colours (1–21). */
function contrast(a, b) {
  const la = luminance(a);
  const lb = luminance(b);
  const [hi, lo] = la >= lb ? [la, lb] : [lb, la];
  return (hi + 0.05) / (lo + 0.05);
}

const HEX = /^#[0-9a-f]{6}$/;

/** Validates one theme against the manifest contract; returns error strings. */
function validate(theme) {
  const errors = [];
  for (const key of ['light', 'dark', 'fg']) {
    if (!HEX.test(theme[key])) {
      errors.push(`${theme.name}.${key} "${theme[key]}" is not a 6-digit #rrggbb hex.`);
    }
  }
  if (errors.length > 0) {
    return errors;
  }
  for (const scheme of ['light', 'dark']) {
    const ratio = contrast(theme.fg, theme[scheme]);
    if (ratio < AA) {
      errors.push(
        `${theme.name}: label ${theme.fg} on the ${scheme} fill ${theme[scheme]} is ` +
          `${ratio.toFixed(2)}:1 — below AA (${AA}:1). Pick a darker/lighter fg or fill.`,
      );
    }
  }
  return errors;
}

/** Renders the CSS override layer for one theme. */
function render(theme) {
  const ring = 'color-mix(in srgb, var(--dm-primary) 55%, transparent)';
  return `/*!
 * @dmaster/ui theme: ${theme.label}
 * Generated by scripts/build-themes.mjs — do not edit by hand.
 * Load AFTER the base @dmaster/ui styles. Recolors the brand in light and dark;
 * the built-in light/dark toggle keeps working.
 */
:root {
  --dm-primary: ${theme.light};
  --dm-primary-fg: ${theme.fg};
  --dm-ring: ${ring};
}
[data-dm-theme='dark'] {
  --dm-primary: ${theme.dark};
  --dm-primary-fg: ${theme.fg};
  --dm-ring: ${ring};
}
`;
}

const allErrors = THEMES.flatMap(validate);
if (allErrors.length > 0) {
  console.error('[build-themes] Contrast/format check failed:\n  ' + allErrors.join('\n  '));
  process.exit(1);
}

const names = new Set();
for (const theme of THEMES) {
  if (names.has(theme.name)) {
    console.error(`[build-themes] Duplicate theme name "${theme.name}".`);
    process.exit(1);
  }
  names.add(theme.name);
}

mkdirSync(outDir, { recursive: true });
for (const theme of THEMES) {
  writeFileSync(join(outDir, `${theme.name}.css`), render(theme), 'utf8');
}

console.log(
  `[build-themes] Wrote ${THEMES.length} theme(s) to dist/dmaster-ui/themes/: ` +
    THEMES.map((t) => t.name).join(', '),
);
